controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

forums:
    path: /forums
    controller: App\Controller\ForumController::index

posts:
    path: /forums/{forum_id}/posts
    controller: App\Controller\PostController::index